<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\ico\网络.ico</ApplicationIcon>
    <AssemblyName>SEU-AutoConnect</AssemblyName>
    <RootNamespace>SEU_AutoConnect</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
    <PackageReference Include="ManagedNativeWifi" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\ico\网络.ico" />
  </ItemGroup>

</Project>
